version: '3.8'

services:
  neuromcp-azuredevops:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5300:5300"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ./config:/app/config
    restart: unless-stopped 