version: '3.8'

services:
  neuromcp-sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Database connection settings
      - DB_SERVER=your-server-name
      - DB_NAME=your-database-name
      - DB_USER=your-username
      - DB_PASSWORD=your-password
      - DB_TRUST_SERVER_CERTIFICATE=true
    volumes:
      - ./config:/app/config
    restart: unless-stopped 