version: '3.8'

services:
  neuromcp-sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - MSSQL_SERVER=your-server-name
      - MSSQL_DATABASE=your-database-name
      - MSSQL_USER=your-username
      - MSSQL_PASSWORD=your-password
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    labels:
      - "com.microsoft.dotnet.version=8.0" 