name: Build and Publish Docker Images

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish-azuredevops:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta-azuredevops
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/neuromcp-azuredevops
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push Azure DevOps image
        uses: docker/build-push-action@v4
        with:
          context: ./NeuroMCP.AzureDevOps
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-azuredevops.outputs.tags }}
          labels: ${{ steps.meta-azuredevops.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Update Docker Hub description for AzureDevOps
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/neuromcp-azuredevops
          short-description: "NeuroMCP server for Azure DevOps integration via MCP protocol"
          readme-filepath: ./NeuroMCP.AzureDevOps/DOCKERHUB.md
          
  publish-sqlserver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta-sqlserver
        uses: docker/metadata-action@v4
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/neuromcp-sqlserver
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push SQL Server image
        uses: docker/build-push-action@v4
        with:
          context: ./NeuroMCP.SqlServer
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta-sqlserver.outputs.tags }}
          labels: ${{ steps.meta-sqlserver.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Update Docker Hub description for SQL Server
        if: github.event_name != 'pull_request'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/neuromcp-sqlserver
          short-description: "NeuroMCP server for SQL Server integration via MCP protocol"
          readme-filepath: ./NeuroMCP.SqlServer/DOCKERHUB.md 